# ClamAV integration
clamav {
    action = "reject";
    scan_mime_parts = true;
    servers = "clamav:3310";
    symbol = "CLAM_VIRUS";
    patterns {
        JUST_EICAR = "^Eicar-Test-Signature$";
    }
}
